/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToC */

#ifndef _Included_JavaToC
#define _Included_JavaToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToC
 * Method:    f
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaToC_f
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
